---
title: "NCUC Disconnection Data"
output: html_document
date: "2023-10-24"
runtime: shiny
---
```{r load, include=FALSE}
library(tidyverse)
library(shiny)
library(dplyr)
library(here)
library(yaml)
library(trend)
library(zoo)
library(Kendall)
library(tseries)
library(conflicted)

disconnections <- read.csv(here("./NCUC_Disconnection_1996_2022.csv"), 
                           stringsAsFactors = TRUE,
                           header = TRUE)

#create a complete Date column, make all N/A's zero
disconnections <- disconnections %>% 
  mutate(Date = make_date(month = Month, year = Year)) %>% replace(is.na(.), 0)
```

```{r select box company, echo=FALSE}
selectInput(inputId = "company",
            label = h3("Select electric utility"), 
            choices = list("Duke Energy Carolinas" = "Duke Energy Carolinas", 
                   "Duke Energy Progress" = "Duke Energy Progress", 
                   "Dominion" = "Dominion",
                   "New River Light & Power" = "New River Light & Power",
                   "Nantahala" = "Nantahala"), 
    selected = "N/A")

selectInput(inputId = "month",
            label = h3("Select month"), 
            choices = list(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), 
    selected = "N/A")

selectInput(inputId = "year",
            label = h3("Select year"), 
            choices = list(2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014,
                           2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005,
                           2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996), 
    selected = "N/A")

value <- function(df, company, month, year) {
  filtered.line <- df %>% 
    dplyr::filter(Company == company, Month == month, Year == year)
  
  return(filtered.line)
}

renderTable(paste(value(disconnections, input$company, input$month, input$year)))
#make table horizontal?

```

```{r base plot, echo=FALSE}

year <- 2010
company <- "Duke Energy Progress"

base.df <- disconnections %>% dplyr::filter(Year == year, Company == company)

base.df$Number_Disconnections_Res <- as.numeric(base.df$Number_Disconnections_Res)

baseplot <- base.df %>%
  ggplot(aes(x=factor(Month, levels=1:12, labels=month.abb),y=Number_Disconnections_Res)) +
  labs(x = "Month", y = "Number of Residential Disconnections") +
  geom_point()
  geom_line()
baseplot


```

```{r bar chart}

barchart <- function(df, month, year) {
  barchartdf <- df %>% dplyr::filter(Year == year & Month == month)

  barchart.plot <- barchartdf %>%
    ggplot(aes(x=Company, y=Number_Disconnections_Res)) +
    geom_col() +
    labs(x ="Company", y ="Number of Residential Disconnections",
         title=paste("Disconnections for", month,"/",year))

  return(barchart.plot)
}

renderPlot(barchart(disconnections, input$month, input$year))

#set theme for plots
#add color to plots

```

```{r base plot with variable input, echo=FALSE}

disconnections$Number_Disconnections_Res <- as.numeric(disconnections$Number_Disconnections_Res)

yearlyplot <- function(df, year, company) {
  yearplot <- df %>% 
  dplyr::filter(Year == year, Company == company) %>%
  ggplot(aes(x=factor(Month, levels=1:12, labels=month.abb),
             y=Number_Disconnections_Res)) + 
  labs(x = "Month", y = "Number of Residential Disconnections") +
  geom_point()
  
  return(yearplot)
  }

renderPlot(yearlyplot(disconnections, input$year, input$company))

```


```{r time series plot}

timeseries <- function(df, company) {
  disconnections.company.ts <- df %>%
    dplyr::filter(Company == company)

  disconnections.plot.ts <- disconnections.company.ts %>%
    ggplot(aes(x=Date, y=Number_Disconnections_Res)) +
    geom_line() +
    labs(x="Date", y="Number of Residential Disconnections")

  return(disconnections.plot.ts)
}

renderPlot(timeseries(disconnections, input$company))
```

```{r pie chart}

# piechart <- function(df, month, year) {
#   piechartdf <- df %>% 
#     dplyr::filter(Year == year & Month == month)
# 
#   return(piechartdf)
#   
#   piechart.disc <- table(piechartdf$Number_Disconnections_Res)
#   
#   #return(piechart.disc)
#   
#   #piechart.labels <- paste(piechartdf$Company)
#   
#   #piechart.plot <- pie(piechart.disc, labels = piechart.labels)
#   
#   #return(piechart.plot)
#   }

```

```{r time series decomp plot}

timeseriesdecomp <- function(df, company) {
  disconnections.company.tsdecomp <- df %>%
    dplyr::filter(Company == company)
  
  disconnections.ts <- ts(disconnections.company.tsdecomp$Number_Disconnections_Res,
                          start=c(1996, 01, 01), frequency=12)
  
  disconnections.decomp <- stl(disconnections.ts, s.window="periodic")
  
  disconnections.plot.tsdecomp <- plot(disconnections.decomp)
  
  return(disconnections.plot.tsdecomp)
}

renderPlot(timeseriesdecomp(disconnections, input$company))

#potentially to visualize performance across companies (time series or initial month)

```

```{r time series analysis}

disconnections.smk <- function(df, company) {
  disconnections.company.ts <- df %>%
  dplyr::filter(Company == company)
  
  disconnections.ts <- ts(disconnections.company.ts$Number_Disconnections_Res,
                          start=c(1996, 01, 01), frequency=12)
  
  smktrends <- SeasonalMannKendall(disconnections.ts)
  
  return(summary(smktrends))
}

renderPrint(paste("The Seasonal Mann-Kendall test results are",disconnections.smk(disconnections, input$company)))


#out of order paste?
```

```{r more plots}
#another time series plot group by year instead of month (sum or average) // methodology for compiling disconnections (repeat customers being disconnected)
#can also look at yearly dataset by picking month (July) // summer yearly series vs winter yearly series
#try to interpolate the N/As
#can compare yearly disconnection values with average temperature for that year in summers and winters 
#scatterplot comparing two utilities (x=utility 1 disconnections, y=utility 2 disconnections)
#population or total customer percentages (in new bar chart)
#facet wrap all utility performances for the year 
#explore potential inflation effects with number of disconnections
#explore potential rate change effects with number of disconnections
#does seasonality actually exist in time series
```

=======
